
root = "."
tmp_dir = "tmp"
build_dir = "tmp/.air"
exclude_dir = ["tmp", "vendor"]
exclude_file = []
include_ext = ["go"]
exclude_ext = ["tpl", "tmpl", "log"]
latency = "1s"
graceful_kill_timeout = "5s"
bin = "make run" 
build_args = [] 
start_hook = "gin --port 3000