// Code generated by MockGen. DO NOT EDIT.
// Source: pkg/repository/interface/admin.go

// Package mock is a generated GoMock package.
package mock

import (
	reflect "reflect"
	time "time"

	domain "github.com/abhinandkakkadi/ecommerce-MoviesGo-gin-clean-arch/pkg/domain"
	models "github.com/abhinandkakkadi/ecommerce-MoviesGo-gin-clean-arch/pkg/utils/models"
	gomock "github.com/golang/mock/gomock"
)

// MockAdminRepository is a mock of AdminRepository interface.
type MockAdminRepository struct {
	ctrl     *gomock.Controller
	recorder *MockAdminRepositoryMockRecorder
}

// MockAdminRepositoryMockRecorder is the mock recorder for MockAdminRepository.
type MockAdminRepositoryMockRecorder struct {
	mock *MockAdminRepository
}

// NewMockAdminRepository creates a new mock instance.
func NewMockAdminRepository(ctrl *gomock.Controller) *MockAdminRepository {
	mock := &MockAdminRepository{ctrl: ctrl}
	mock.recorder = &MockAdminRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAdminRepository) EXPECT() *MockAdminRepositoryMockRecorder {
	return m.recorder
}

// AddGenre mocks base method.
func (m *MockAdminRepository) AddGenre(genre models.CategoryUpdate) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddGenre", genre)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddGenre indicates an expected call of AddGenre.
func (mr *MockAdminRepositoryMockRecorder) AddGenre(genre interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddGenre", reflect.TypeOf((*MockAdminRepository)(nil).AddGenre), genre)
}

// AmountDetails mocks base method.
func (m *MockAdminRepository) AmountDetails() (models.DashboardAmount, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AmountDetails")
	ret0, _ := ret[0].(models.DashboardAmount)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AmountDetails indicates an expected call of AmountDetails.
func (mr *MockAdminRepositoryMockRecorder) AmountDetails() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AmountDetails", reflect.TypeOf((*MockAdminRepository)(nil).AmountDetails))
}

// CheckAdminAvailability mocks base method.
func (m *MockAdminRepository) CheckAdminAvailability(admin models.AdminSignUp) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CheckAdminAvailability", admin)
	ret0, _ := ret[0].(bool)
	return ret0
}

// CheckAdminAvailability indicates an expected call of CheckAdminAvailability.
func (mr *MockAdminRepositoryMockRecorder) CheckAdminAvailability(admin interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckAdminAvailability", reflect.TypeOf((*MockAdminRepository)(nil).CheckAdminAvailability), admin)
}

// CreateAdmin mocks base method.
func (m *MockAdminRepository) CreateAdmin(admin models.AdminSignUp) (models.AdminDetailsResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateAdmin", admin)
	ret0, _ := ret[0].(models.AdminDetailsResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateAdmin indicates an expected call of CreateAdmin.
func (mr *MockAdminRepositoryMockRecorder) CreateAdmin(admin interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateAdmin", reflect.TypeOf((*MockAdminRepository)(nil).CreateAdmin), admin)
}

// DashBoardOrder mocks base method.
func (m *MockAdminRepository) DashBoardOrder() (models.DashboardOrder, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DashBoardOrder")
	ret0, _ := ret[0].(models.DashboardOrder)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DashBoardOrder indicates an expected call of DashBoardOrder.
func (mr *MockAdminRepositoryMockRecorder) DashBoardOrder() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DashBoardOrder", reflect.TypeOf((*MockAdminRepository)(nil).DashBoardOrder))
}

// DashBoardProductDetails mocks base method.
func (m *MockAdminRepository) DashBoardProductDetails() (models.DashBoardProduct, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DashBoardProductDetails")
	ret0, _ := ret[0].(models.DashBoardProduct)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DashBoardProductDetails indicates an expected call of DashBoardProductDetails.
func (mr *MockAdminRepositoryMockRecorder) DashBoardProductDetails() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DashBoardProductDetails", reflect.TypeOf((*MockAdminRepository)(nil).DashBoardProductDetails))
}

// DashboardUserDetails mocks base method.
func (m *MockAdminRepository) DashboardUserDetails() (models.DashboardUser, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DashboardUserDetails")
	ret0, _ := ret[0].(models.DashboardUser)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DashboardUserDetails indicates an expected call of DashboardUserDetails.
func (mr *MockAdminRepositoryMockRecorder) DashboardUserDetails() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DashboardUserDetails", reflect.TypeOf((*MockAdminRepository)(nil).DashboardUserDetails))
}

// Delete mocks base method.
func (m *MockAdminRepository) Delete(genre_id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", genre_id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockAdminRepositoryMockRecorder) Delete(genre_id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockAdminRepository)(nil).Delete), genre_id)
}

// FilteredSalesReport mocks base method.
func (m *MockAdminRepository) FilteredSalesReport(startTime, endTime time.Time) (models.SalesReport, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FilteredSalesReport", startTime, endTime)
	ret0, _ := ret[0].(models.SalesReport)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FilteredSalesReport indicates an expected call of FilteredSalesReport.
func (mr *MockAdminRepositoryMockRecorder) FilteredSalesReport(startTime, endTime interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FilteredSalesReport", reflect.TypeOf((*MockAdminRepository)(nil).FilteredSalesReport), startTime, endTime)
}

// GetGenres mocks base method.
func (m *MockAdminRepository) GetGenres() ([]domain.Genre, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetGenres")
	ret0, _ := ret[0].([]domain.Genre)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetGenres indicates an expected call of GetGenres.
func (mr *MockAdminRepositoryMockRecorder) GetGenres() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetGenres", reflect.TypeOf((*MockAdminRepository)(nil).GetGenres))
}

// GetUserByID mocks base method.
func (m *MockAdminRepository) GetUserByID(id string) (domain.Users, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserByID", id)
	ret0, _ := ret[0].(domain.Users)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserByID indicates an expected call of GetUserByID.
func (mr *MockAdminRepositoryMockRecorder) GetUserByID(id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserByID", reflect.TypeOf((*MockAdminRepository)(nil).GetUserByID), id)
}

// GetUsers mocks base method.
func (m *MockAdminRepository) GetUsers(page, count int) ([]models.UserDetailsAtAdmin, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUsers", page, count)
	ret0, _ := ret[0].([]models.UserDetailsAtAdmin)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUsers indicates an expected call of GetUsers.
func (mr *MockAdminRepositoryMockRecorder) GetUsers(page, count interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUsers", reflect.TypeOf((*MockAdminRepository)(nil).GetUsers), page, count)
}

// LoginHandler mocks base method.
func (m *MockAdminRepository) LoginHandler(adminDetails models.AdminLogin) (domain.Admin, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LoginHandler", adminDetails)
	ret0, _ := ret[0].(domain.Admin)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// LoginHandler indicates an expected call of LoginHandler.
func (mr *MockAdminRepositoryMockRecorder) LoginHandler(adminDetails interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LoginHandler", reflect.TypeOf((*MockAdminRepository)(nil).LoginHandler), adminDetails)
}

// TotalRevenue mocks base method.
func (m *MockAdminRepository) TotalRevenue() (models.DashboardRevenue, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "TotalRevenue")
	ret0, _ := ret[0].(models.DashboardRevenue)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// TotalRevenue indicates an expected call of TotalRevenue.
func (mr *MockAdminRepositoryMockRecorder) TotalRevenue() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TotalRevenue", reflect.TypeOf((*MockAdminRepository)(nil).TotalRevenue))
}

// UpdateBlockUserByID mocks base method.
func (m *MockAdminRepository) UpdateBlockUserByID(user domain.Users) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateBlockUserByID", user)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateBlockUserByID indicates an expected call of UpdateBlockUserByID.
func (mr *MockAdminRepositoryMockRecorder) UpdateBlockUserByID(user interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateBlockUserByID", reflect.TypeOf((*MockAdminRepository)(nil).UpdateBlockUserByID), user)
}
